// Code generated by "stringer -type TokenType scanner.go"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HashLabel-1]
	_ = x[DollarLabel-2]
	_ = x[PlusLabel-3]
	_ = x[Line-4]
	_ = x[String-5]
	_ = x[Number-6]
	_ = x[Comment-7]
	_ = x[BlockComment-8]
	_ = x[HashEnd-9]
}

const _TokenType_name = "HashLabelDollarLabelPlusLabelLineStringNumberCommentBlockCommentHashEnd"

var _TokenType_index = [...]uint8{0, 9, 20, 29, 33, 39, 45, 52, 64, 71}

func (i TokenType) String() string {
	i -= 1
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
